config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tickets#index'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :tickets, only: [:create]
    end
  end

  resources :tickets, only: %i[index show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/excavator.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: excavators
#
#  id           :bigint           not null, primary key
#  address      :string           not null
#  company_name :string           not null
#  crew_onsite  :boolean          default(FALSE), not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  ticket_id    :bigint           not null
#
# Indexes
#
#  index_excavators_on_ticket_id  (ticket_id)
#
# Foreign Keys
#
#  fk_rails_...  (ticket_id => tickets.id)
#
class Excavator < ApplicationRecord
  belongs_to :ticket

  validates :company_name, :address, presence: true
end

app/models/ticket.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: tickets
#
#  id                            :bigint           not null, primary key
#  additional_service_area_codes :text             default([]), is an Array
#  digsite_info_text             :text             not null
#  primary_service_area_code     :string           not null
#  request_action                :string           not null
#  request_number                :string           not null
#  request_type                  :string           not null
#  response_due_date_time        :datetime         not null
#  sequence_number               :integer          not null
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#
class Ticket < ApplicationRecord
  has_one :excavator, dependent: :destroy

  validates :request_number, :sequence_number, :request_type, :request_action,
            :response_due_date_time, :primary_service_area_code, :primary_service_area_code,
            :additional_service_area_codes, :digsite_info_text, presence: true
end

app/controllers/api/v1/tickets_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class TicketsController < ApiController
      def create
        @record = Tickets::CreateService.call(ticket_params, excavator_params)
        if @record.errors.empty?
          render :show, status: :created
        else
          render json: { errors: @record.errors.full_messages }, status: :unprocessable_entity
        end
      end

      private

      def ticket_params
        params.permit(:request_number, :sequence_number, :request_type, :request_action,
                      { date_times: :response_due_date_time }, { excavation_info: { digsite_info: :well_known_text } },
                      { service_area: { primary_service_area_code: :sa_code, additional_service_area_codes:
                        { sa_code: [] } } })
      end

      def excavator_params
        params.require(:excavator).permit(:company_name, :address, :city, :state, :zip, :crew_onsite)
      end
    end
  end
end

app/controllers/api_controller.rb
# frozen_string_literal: true

class ApiController < ActionController::API
  before_action :transform_params

  private

  def transform_params
    params.deep_transform_keys!(&:underscore)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::API
  include ActionView::Layouts
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all
  end

  def show
    @ticket = Ticket.find(params[:id]).decorate
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Application Name</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="https://horizon-tailwind-react-git-tailwind-components-horizon-ui.vercel.app/static/css/main.ad49aa9b.css" />
  <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" />
</head>
  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/tickets/_excavator_details.html.erb
<div class="flex flex-col items-start justify-center rounded-2xl bg-white bg-clip-border px-3 py-4 shadow-3xl shadow-shadow-500 dark:!bg-navy-700 dark:shadow-none">
  <p class="text-xl pb-2 text-navy-800"><%= t('.title', id: excavator.id) %></p>
  <p class="text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.company_name') %></span>
    <span class="text-gray-400"><%= excavator.company_name %></span>
  </p>
  <p class="text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.address') %></span>
    <span class="text-gray-400"><%= excavator.address %></span>
  </p>
  <p class="text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.crew_onsite') %></span>
    <span class="text-gray-400"><%= excavator.crew_onsite %></span>
  </p>
</div>

app/views/tickets/_ticket.html.erb
<div class="flex flex-col items-start justify-center rounded-2xl bg-white bg-clip-border px-3 py-4 shadow-3xl shadow-shadow-500 dark:!bg-navy-700 dark:shadow-none">
  <p class="text-xl pb-2 text-navy-800"><%= t('.title', id: ticket.id) %></p>
  <p class="request_number text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.request_number') %></span>
    <span class="text-gray-400"><%= ticket.request_number %></span>
  </p>
  <p class="sequence_number text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.sequence_number') %></span>
    <span class="text-gray-400"><%= ticket.sequence_number %></span>
  </p>
  <p class="request_type text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.request_type') %></span>
    <span class="text-gray-400"><%= ticket.request_type %></span>
  </p>
  <p class="request_action text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.request_action') %></span>
    <span class="text-gray-400"><%= ticket.request_action %></span>
  </p>
  <div class='pt-3'>
    <%= link_to ticket_path(ticket.id) do %>
      <button class="details-btn bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ">
        <%= t('.details') %>
      </button>
    <% end %>
  </div>
</div>

app/views/tickets/_ticket_details.html.erb
<div class="flex flex-col items-start justify-center rounded-2xl bg-white bg-clip-border px-3 py-4 shadow-3xl shadow-shadow-500 dark:!bg-navy-700 dark:shadow-none">
  <p class="text-xl pb-2 text-navy-800"><%= t('.title', id: ticket.id) %></p>
  <p class="text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.request_number') %></span>
    <span class="text-gray-400"><%= ticket.request_number %></span>
  </p>
  <p class="text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.sequence_number') %></span>
    <span class="text-gray-400"><%= ticket.sequence_number %></span>
  </p>
  <p class="text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.request_type') %></span>
    <span class="text-gray-400"><%= ticket.request_type %></span>
  </p>
  <p class="text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.request_action') %></span>
    <span class="text-gray-400"><%= ticket.request_action %></span>
  </p>
    <p class="text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.response_due_date_time') %></span>
    <span class="text-gray-400"><%= ticket.response_due_date_time %></span>
  </p>
    <p class="text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.primary_service_area_code') %></span>
    <span class="text-gray-400"><%= ticket.primary_service_area_code %></span>
  </p>
    <p class="text-sm font-medium dark:text-white">
    <span class="text-gray-700"><%= t('.additional_service_area_codes') %></span>
    <span class="text-gray-400"><%= ticket.additional_service_area_codes.join(', ') %></span>
  </p>
</div>

app/views/tickets/index.html.erb
<div class="flex flex-col justify-center items-center h-[100vh]">
    <div class="relative flex flex-col items-center rounded-[20px] w-[700px] max-w-[95%] mx-auto bg-white bg-clip-border shadow-3xl shadow-shadow-500 dark:!bg-navy-800 dark:text-white dark:!shadow-none p-3">
        <div class="mt-2 mb-8 w-full">
            <h4 class="title px-2 text-xl font-bold text-navy-700 dark:text-white">
              <%= t('.title') %>
            </h4>
        </div>
        <div class="tickets grid grid-cols-2 gap-4 px-2 w-full">
            <%= render @tickets %>
        </div>
    </div>
</div>

app/views/tickets/show.html.erb
<div class="flex flex-col justify-center items-center h-[100vh] mb-4">
    <div class="relative flex flex-col items-center rounded-[20px] w-[700px] max-w-[95%] mx-auto bg-white bg-clip-border shadow-3xl shadow-shadow-500 dark:!bg-navy-800 dark:text-white dark:!shadow-none p-3">
        <div class="mt-2 mb-4 w-full">
            <h4 class="px-2 text-xl font-bold text-navy-700 dark:text-white">
              <%= t('.title') %>
            </h4>
        </div>
        <div class="grid grid-cols-1 gap-4 px-2 w-full  mb-4">
            <%= render 'ticket_details', ticket: @ticket %>
        </div>
        <div class="grid grid-cols-1 gap-4 px-2 w-full">
            <%= render 'excavator_details', excavator: @ticket.excavator %>
        </div>
    </div>
</div>

<%= js_map @ticket.digging_coordinates %>